### client Token - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImNsaWVudCIsImlhdCI6MTc0NDczNDY4MCwiZXhwIjoxNzQ0ODIxMDgwfQ.y8LSAmsr72urok4FW7qWZwVhRsJgHJkowd9sCkGDvJE
### freelancer - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzcwMjMsImV4cCI6MTc0NDgyMzQyM30.UTqz-4qTQ6fVSHipYSc7l_92JdwSXNwWRxTuGMl03yw

### GET All Chats - Retrieves all chats in which the authenticated user participates
# client
GET http://localhost:3000/api/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzcwMjMsImV4cCI6MTc0NDgyMzQyM30.UTqz-4qTQ6fVSHipYSc7l_92JdwSXNwWRxTuGMl03yw
Content-Type: application/json


### POST Create Chat
# Attempts to create a new chat
# If a chat already exists return the existing chat
POST http://localhost:3000/api/chats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImNsaWVudCIsImlhdCI6MTc0NDczNDY4MCwiZXhwIjoxNzQ0ODIxMDgwfQ.y8LSAmsr72urok4FW7qWZwVhRsJgHJkowd9sCkGDvJE
Content-Type: application/json

{
  "client_id": 2
}


### GET Chat Messages
# Retrieves all messages for the chat with ID 10.
GET http://localhost:3000/api/chats/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzcwMjMsImV4cCI6MTc0NDgyMzQyM30.UTqz-4qTQ6fVSHipYSc7l_92JdwSXNwWRxTuGMl03yw
Content-Type: application/json


### POST Send Message
# Sends a new message in the chat with ID 10.
# The message is also broadcast via Socket.IO to all users in the chat room.
POST http://localhost:3000/api/chats/1/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImNsaWVudCIsImlhdCI6MTc0NDczNDY4MCwiZXhwIjoxNzQ0ODIxMDgwfQ.y8LSAmsr72urok4FW7qWZwVhRsJgHJkowd9sCkGDvJE
Content-Type: application/json

{
  "message": "I need my car fixed"
}

### Mark All Messages in Chat as Read
# This POST request marks all unread messages in chat with ID 12 as read.
# It expects that the authenticated user (obtained from the JWT token) is not the sender of the messages.
POST http://localhost:3000/api/chats/1/messages/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzcwMjMsImV4cCI6MTc0NDgyMzQyM30.UTqz-4qTQ6fVSHipYSc7l_92JdwSXNwWRxTuGMl03yw
Content-Type: application/json

git config --global user.email "tamara.solime1@gmail.com"
  git config --global user.name "Solime421"