### OFFER ENDPOINTS

### POST Send Offer
POST http://localhost:3000/api/offers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDU0MjAzNjcsImV4cCI6MTc0NTUwNjc2N30.us1tdtiKjLMpd8M87nEmmPQeqFeNLIOY0_69mDaJvnU
Content-Type: application/json

{
  "chatId": 2,
  "offer_name": "Whell fix"
}


### GET Offer by Chat
# Used by a client to view the latest pending offer for a given chat
GET http://localhost:3000/api/offers/chat/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0MjAyNDcsImV4cCI6MTc0NTUwNjY0N30.Qdf4bHE9H4hpaorvEuniFtO2KjPRtDsnrgXsBkU_gT4
Content-Type: application/json


### POST Accept Offer
POST http://localhost:3000/api/offers/5/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0MjAyNDcsImV4cCI6MTc0NTUwNjY0N30.Qdf4bHE9H4hpaorvEuniFtO2KjPRtDsnrgXsBkU_gT4
Content-Type: application/json


### ORDER ENDPOINTS

### GET All Orders
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3NDkxNDQsImV4cCI6MTc0NDgzNTU0NH0.uPLSMIDgjQgWF2RX3nCSLifeoZDMesWpBbgKW2XWIt4
Content-Type: application/json


### PUT Update Order Status
PUT http://localhost:3000/api/orders/10/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3NDk1NzYsImV4cCI6MTc0NDgzNTk3Nn0.nmgSyXXZu4JT93JY9NtsD0LNF518-KSBsxnXLZdaEDQ
Content-Type: application/json

{
  "status": true
}