### GET all Portfolio Images
GET http://localhost:3000/api/privatePortfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQ0MzcwMjUyLCJleHAiOjE3NDQ0NTY2NTJ9.0qrRpCufVHtWmwMo4we2nLzt2agFRb3JnRcAlSgsKKo
Content-Type: application/json

### POST Add a New Portfolio Image
POST http://localhost:3000/api/privatePortfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsInJvbGUiOiJmcmVlbGFuY2VyIiwiaWF0IjoxNzQ0MzcwMjUyLCJleHAiOjE3NDQ0NTY2NTJ9.0qrRpCufVHtWmwMo4we2nLzt2agFRb3JnRcAlSgsKKo
Content-Type: application/json

{
  "imageUrl": "https://janko-3.com/image1.jpg"
}

### DELETE a Portfolio Image
### 5 is an image id
DELETE http://localhost:3000/api/privatePortfolio/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQyNzgyMzcsImV4cCI6MTc0NDM2NDYzN30.s2KdR8vsQV_8i34VC2vxT2eIUdBEPQFNBZmjiYbNWCI
Content-Type: application/json
