###
### GET All Portfolio Images for Freelancer
GET http://localhost:3000/api/privateFreelancerProfiles/portfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDU1MDEwNzIsImV4cCI6MTc0NTU4NzQ3Mn0.XeRjwNd5aOrU6R6vJd9UYCTREXOGA0Or23s-lJx0kUU
Content-Type: application/json

### POST Upload Portfolio Image
# Replace the path with the full path to your local file.
POST http://localhost:3000/api/privateFreelancerProfiles/portfolio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDU1MDEwNzIsImV4cCI6MTc0NTU4NzQ3Mn0.XeRjwNd5aOrU6R6vJd9UYCTREXOGA0Or23s-lJx0kUU
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="newnew.jpg"
Content-Type: image/jpeg

< C:\Users\Vrn\Pictures\FIXD\portfolio pictures\branko-sa.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### DELETE a Portfolio Image
# Deletes the portfolio image with ID 4.
DELETE http://localhost:3000/api/privateFreelancerProfiles/portfolio/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDUxNDQxOTksImV4cCI6MTc0NTIzMDU5OX0.TiaRosFuUMlZAWRMOQ9fKy02x6pgmZWbpPfV1c6GRQA
Content-Type: application/json