### GET Personal Profile
GET http://localhost:3000/api/privateProfiles/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0MDY2NjAsImV4cCI6MTc0NTQ5MzA2MH0.95A5BnMPGJmFZxb5QMHD5OEPwfoJkSZA_2KVqBOgCAo
Content-Type: application/json

###
### POST Update Personal Data
POST http://localhost:3000/api/privateProfiles/personal-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDUzOTc4MDMsImV4cCI6MTc0NTQ4NDIwM30.0fN1ApgvD7y_AbOYCKcVn4z_kjvVP_0D07NYDTZeyXY
Content-Type: application/json

{
  "firstName": "Tamara",
  "lastName": "Sikimic",
  "phone": "0607340258"
}

###
### POST Update Profile Picture
POST http://localhost:3000/api/privateProfiles/profile-picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0ODA5NjksImV4cCI6MTc0NTU2NzM2OX0.ks-0WT1nBRq7BnXBWTnpt88Z5a4NKieNX1ZYviIOXpY
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="avatar.jpg"
Content-Type: image/jpeg

< C:\Users\Vrn\Pictures\coffee.bmp
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
### POST Update Location
POST http://localhost:3000/api/privateProfiles/location
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzQyNjIsImV4cCI6MTc0NDgyMDY2Mn0._yMLgk5baCtQnWp_ai6P4Fep7mOSB803bdxTScgJfEI
Content-Type: application/json

{
  "location": {
    "lat": 49,
    "lng": -49,
    "zip": "34000",
    "city": "Beograd",
    "country": "Serbia",
    "address": "Obelicev Venac"
  }
}
