### GET Freelancer Public Profile
# Simulise kako KLIENT gleda profil Majstora. Znaci, message should be enabled.
GET http://localhost:3000/api/publicProfiles/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ0NTc2MjcsImV4cCI6MTc0NDU0NDAyN30.aGa9txadGEJZIEF10wwTwcYjWMFzcit4Hz6AUsTJWQ4
Content-Type: application/json

### GET Freelancer Public Profile
# Simulise kako MAJSTOR gleda profil Majstora. Znaci, message should be FALSE.
GET http://localhost:3000/api/publicProfiles/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQyNzgwMjAsImV4cCI6MTc0NDM2NDQyMH0.ISxV-xHrpVgd83ai3beRgbNZkxeTm6B-RCh2xSFxSDs
Content-Type: application/json


### GET Client Public Profile
# Simulise kako MAJSTOR gleda profil Klienta.
GET http://localhost:3000/api/publicProfiles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ0NTc2MjcsImV4cCI6MTc0NDU0NDAyN30.aGa9txadGEJZIEF10wwTwcYjWMFzcit4Hz6AUsTJWQ4
Content-Type: application/json
