### GET Freelancer Public Profile
# Simulise kako KLIENT gleda profil Majstora. Znaci, message should be enabled.
GET http://localhost:3000/api/publicProfile/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0MDY2NjAsImV4cCI6MTc0NTQ5MzA2MH0.95A5BnMPGJmFZxb5QMHD5OEPwfoJkSZA_2KVqBOgCAo
Content-Type: application/json

### GET Freelancer Public Profile
# Simulise kako MAJSTOR gleda profil Majstora. Znaci, message should be FALSE.
GET http://localhost:3000/api/publicProfile/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3MzQyNjIsImV4cCI6MTc0NDgyMDY2Mn0._yMLgk5baCtQnWp_ai6P4Fep7mOSB803bdxTScgJfEI
Content-Type: application/json


### GET Client Public Profile
# Simulise kako MAJSTOR gleda profil Klienta.
GET http://localhost:3000/api/publicProfile/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3NDc1MzgsImV4cCI6MTc0NDgzMzkzOH0.uPiwaLFd-mMik5f-y-zBwBon45DcuS9_rqsVcvnA-t8
Content-Type: application/json
