### GET Freelancer Public Profile
# Simulise kako KLIENT gleda profil Majstora. Znaci, message should be enabled.
GET http://localhost:3000/api/publicProfiles/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImNsaWVudCIsImlhdCI6MTc0NDI3ODE3OCwiZXhwIjoxNzQ0MzY0NTc4fQ.v-6wOwGNlcZiX6twgeBu-nsaD4wC_u606ZR8CUzNicI
Content-Type: application/json

### GET Freelancer Public Profile
# Simulise kako MAJSTOR gleda profil Majstora. Znaci, message should be FALSE.
GET http://localhost:3000/api/publicProfiles/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQyNzgwMjAsImV4cCI6MTc0NDM2NDQyMH0.ISxV-xHrpVgd83ai3beRgbNZkxeTm6B-RCh2xSFxSDs
Content-Type: application/json


### GET Client Public Profile
# Simulise kako MAJSTOR gleda profil Klienta.
GET http://localhost:3000/api/publicProfiles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQyNzgwMjAsImV4cCI6MTc0NDM2NDQyMH0.ISxV-xHrpVgd83ai3beRgbNZkxeTm6B-RCh2xSFxSDs
Content-Type: application/json
