### POST Leave a Review
POST http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTUsInJvbGUiOiJjbGllbnQiLCJpYXQiOjE3NDU0MjAyNDcsImV4cCI6MTc0NTUwNjY0N30.Qdf4bHE9H4hpaorvEuniFtO2KjPRtDsnrgXsBkU_gT4
Content-Type: application/json

{
  "orderId": 5,
  "revieweeId": 3,
  "rating": 5,
  "comment": "Good work overall, but communication could have been a bit faster. Still very happy with the result. The final deliverable was good, but we had a few hiccups on scope. Overall a positive experience.."
}

### GET Freelancer Reviews (Only for Freelancer)
GET http://localhost:3000/api/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6ImZyZWVsYW5jZXIiLCJpYXQiOjE3NDQ3OTg0NzksImV4cCI6MTc0NDg4NDg3OX0.NDqYB6LBM2HZtP8RroxQ5OvoISBjRgStQyRo-_GRcJ0
Content-Type: application/json